### ISSUE TITLE
Should we move to UTF-8

### ISSUE THREAD

**Issue by jasrys** [jasrys/cwr-json#51]
Some socieites can only handle latin-1, but JSON is inherently UTF-8

Maybe we do UTF-8 for JSON only and leave EDI as latin-1

**Comment by alv909** [comment]
Exactly, the EDI version of CWR is not touched by our work on CWR 3.1-json.

Any Society or DSP or Publisher, and we want them all, that adopts JSON as the file format for CWR, MUST handle UTF-8. 
This is not an "opinion" but simply the JSON specification, which is crystal clear on this matter.

Please see below (incl. the source link), they even emphasize the word MUST, the emphasis is NOT mine :-)

[8] String and Character Issues
[8.1] Character Encoding

   **JSON text exchanged between systems that are not part of a closed
   ecosystem MUST be encoded using UTF-8.**

   Previous specifications of JSON have not required the use of UTF-8
   when transmitting JSON text.  However, the vast majority of JSON-
   based software implementations have chosen to use the UTF-8 encoding,
   to the extent that it is the only encoding that achieves
   interoperability.

Source: https://datatracker.ietf.org/doc/html/rfc8259

PS: As Ray pointed out correctly in todays discussion, this has nothing to do with potential Societies legacy databases that might store data in a different way. These two things are decoupled from each other.

Let us positively surprise Publishers, Societies and DSPs (and DDEX ;-) by doing the right thing on this and other matters of the new standard.

**Comment by alv909** [comment]
Or to phrase it in more political terms:
- whoever at CISAC greenlighted this Working Group on CWR 3.1-json implicitely greenlighted UTF-8 as the character encoding, by definition of JSON
- second, if we would "dare" put out a CWR 3.1-json in a non-UTF-8 character encoding (say Latin 1), or just hint at making this optional, we would be the laughing stock of not only the music industry, the DSPs but also the entire IT industry; nobody would ever take us members of this group or CISAC seriously anymore

**Comment by jasrys** [comment]
Discussed Oct 10 and agreed to move forward with UTF-8
